### PR TITLE
Various enhancements

### PR DESCRIPTION
**Pull request by iSapozhnik**

### CODE REVIEW

**Comment by PhilippeWeidmann** [comment]
Hi,
thank you for your great PR while testing it I noticed that you removed the height constraint which makes the notification with only a title (eg. "Safari pasted from Notes") a bit too small.
Simulator Screen Shot - iPhone 12 - 2021-06-23 at 21 25 02
Was it done on purpose ? If yes I want to stick as close as possible as the native one, anyway would you be okay to fix the PR to keep the large height 😊 ?

**Comment by iSapozhnik** [comment]
Yeah so since now subtitle can support multiple lines I thought that having a strict height constraint won't make too much sense because now the height is defined by the content. But if you want to have as close to the native look and feel as possible - we can make height constraint `greaterOrEqual` 50. In this way it still can expand in case of a big subtitle but will remain 50pt in case if we have title only. What do you think?

**Comment by PhilippeWeidmann** [comment]
Using `greaterOrEqual` would be perfect 👌

**Comment by iSapozhnik** [comment]
Hey @PhilippeWeidmann, and sorry for my late reply. Ive update the PR.

**Review by PhilippeWeidmann — APPROVED** [review]

**Comment by PhilippeWeidmann** [comment]
Looking great ! Thank you for your PR 😊

**Pull request merged**
